[project]
name = "simple-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "fastmcp>=4.0.3",
    "llama-cloud-services>=0.6.94",
    "llama-index>=0.14.24",
    "python-dotenv>=1.2.3",
]

[project.scripts]
simple-rag = "simple_rag:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
